---
- name: Configure all Linux VMs
  hosts: all
  become: true
  tasks:
    - name: Disable SELinux (only if available)
      command: setenforce 0
      ignore_errors: yes
      when: ansible_facts['os_family'] == "RedHat"

    - name: Disable SELinux in configuration file (only if available)
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      when: ansible_facts['os_family'] == "RedHat"

    - name: Disable Firewalld (only if available)
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

- name: Configure Frontend Servers
  hosts: frontend
  become: true
  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Configure Nginx for Proxying
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        content: |
          server {
              listen 80;
              location / {
                  proxy_pass http://u21.local:19999;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

- name: Configure Backend Servers
  hosts: backend
  become: true
  tasks:
    - name: Install Netdata
      apt:
        name: netdata
        state: present

    - name: Allow Netdata to run on port 19999
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^# bind to = 127.0.0.1'
        line: 'bind to = 0.0.0.0'

    - name: Restart Netdata
      service:
        name: netdata
        state: restarted

